// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJcrSx-B_QsLn-FNfGQbbSa8AF9TYOos',
    appId: '1:862590848178:web:481589f82ce34066820dab',
    messagingSenderId: '862590848178',
    projectId: 'paddyai',
    authDomain: 'paddyai.firebaseapp.com',
    storageBucket: 'paddyai.firebasestorage.app',
    measurementId: 'G-89SF26RVTV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQW3mA5rsxRD4ZY1wue5phk-nnqrkZto',
    appId: '1:862590848178:ios:1d10065867afb3f8820dab',
    messagingSenderId: '862590848178',
    projectId: 'paddyai',
    storageBucket: 'paddyai.firebasestorage.app',
    iosBundleId: 'com.example.paddyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoQW3mA5rsxRD4ZY1wue5phk-nnqrkZto',
    appId: '1:862590848178:ios:1d10065867afb3f8820dab',
    messagingSenderId: '862590848178',
    projectId: 'paddyai',
    storageBucket: 'paddyai.firebasestorage.app',
    iosBundleId: 'com.example.paddyai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJcrSx-B_QsLn-FNfGQbbSa8AF9TYOos',
    appId: '1:862590848178:web:5e14c55afaac49ba820dab',
    messagingSenderId: '862590848178',
    projectId: 'paddyai',
    authDomain: 'paddyai.firebaseapp.com',
    storageBucket: 'paddyai.firebasestorage.app',
    measurementId: 'G-5LBMP25Z60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQII0PFMmpZnjmYFHuoaxoBIPmlzmKwc',
    appId: '1:862590848178:android:c23ece4fc6784781820dab',
    messagingSenderId: '862590848178',
    projectId: 'paddyai',
    storageBucket: 'paddyai.firebasestorage.app',
  );

}